import PageHeader from '../components/PageHeader';

function Disclaimer() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <PageHeader 
        title="Disclaimer"
        subtitle="Important information about our service"
      />
      
      <div className="bg-white shadow-sm rounded-lg p-6 sm:p-8">
        <div className="space-y-6 text-gray-600">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. General Information</h2>
            <p>
              The information provided by TikTok Hashtag Generator is for general informational purposes only. 
              All information on the site is provided in good faith, however, we make no representation or warranty 
              of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, 
              or completeness of any information on the site.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. No Affiliation with TikTok</h2>
            <p>
              TikTok Hashtag Generator is not affiliated with, endorsed by, or in any way officially connected 
              with TikTok or any of its subsidiaries or affiliates. The official TikTok website can be found at 
              <a href="https://www.tiktok.com" className="text-blue-600 hover:text-blue-800 ml-1" target="_blank" rel="noopener noreferrer">
                www.tiktok.com
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Results and Performance</h2>
            <p>
              The hashtags generated by our tool are suggestions based on current trends and algorithms. 
              We do not guarantee specific results or performance improvements for your TikTok content. 
              Success on TikTok depends on many factors beyond hashtag usage.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. External Links</h2>
            <p>
              Our website may contain links to external websites that are not provided or maintained by us. 
              We do not guarantee the accuracy, relevance, timeliness, or completeness of any information 
              on these external websites.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Service Availability</h2>
            <p>
              We strive to provide uninterrupted service, but we make no guarantees about the availability 
              or functionality of our hashtag generator. The service may experience delays or downtime due 
              to maintenance, updates, or factors beyond our control.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Use at Your Own Risk</h2>
            <p>
              Your use of our hashtag generator is at your sole risk. The service is provided on an "AS IS" 
              and "AS AVAILABLE" basis. We reserve the right to modify or discontinue the service at any time 
              without notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Changes to Disclaimer</h2>
            <p>
              We reserve the right to modify this disclaimer at any time without prior notice. By using our 
              website, you agree to be bound by the current version of this disclaimer.
            </p>
          </section>

          <section className="mt-8 pt-6 border-t border-gray-200">
            <p className="text-sm text-gray-500">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}

export default Disclaimer; 